version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_DB=notify_and_comment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=baloghlan1234
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
